version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      PG_USER: postgres
      PG_PASSWORD: dbWIOVHoEoUMyZfmLvJtNFajzpVSonKUD
      PG_DATABASE: railway
    ports:
      - "26983:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  league-application:
    build: .
    container_name: league-application
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_USER: postgres
      PG_PASSWORD: bWIOVHoEoUMyZfmLvJtNFajzpVSonKUD
      PG_DATABASE: railway
      PG_PORT: 26983
    command: ["./main"]

volumes:
  postgres_data: